NAME := cdt_test
DEPENDENCIES :=
LIBS :=
INCLUDE_DIRS := -I../../lib

# [exec|shared|static]
BIN_TYPE := static

INSTALL_DIR := cdt/test
#No binary to install
INSTALL_BIN_DIR := 

# TEST_DIR := ./_test
# TEST_EXEC := cdt_app_test.exe

# CXX := g++
# CFLAGS := -Wall -Werror -std=gnu++11 -I/usr/local/include

# SRC_DIR := ./src
# TMP_DIR := ./tmp
# OBJ_DIR := $(TMP_DIR)/obj
# DEP_DIR := $(TMP_DIR)/depend
# BIN_DIR := ./bin

include ../Makefile.generic

# Your targets