NAME := cdt_core
DEPENDENCIES := 
LIBS := 
INCLUDE_DIRS := -I../../lib

BIN_TYPE := shared

INSTALL_DIR := cdt/core

# TEST_DIR ?= ./_test
# TEST_BIN ?= $(NAME)_test.exe
# TEST_EXEC ?= $(TEST_DIR)/bin/$(TEST_BIN)

# CXX ?= g++
# CFLAGS ?= -Wall -Werror -std=gnu++11 -I/usr/local/include 

# SRC_DIR ?= ./src
# TMP_DIR ?= ./tmp
# OBJ_DIR ?= $(TMP_DIR)/obj
# DEP_DIR ?= $(TMP_DIR)/depend
# BIN_DIR ?= ./bin
# INC_DIR ?= $(SRC_DIR)/includes
# INSTALL_BIN_DIR ?= $(INSTALL_DIR)/bin
# INSTALL_INC_DIR ?= $(INSTALL_DIR)/include

include ../Makefile.generic

# Your targets

test: